config/routes.rb
Rails.application.routes.draw do


  get '/login' => 'session#new'  #sign in
  post '/login' => 'session#create'  #route to which sign in form is posted
  delete '/login' => 'session#destroy' #path users use to log out.


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"static_pages#home"


  resources :users

  resources :conflicts

  get '/conflicts/:id/follow'=>'conflicts#follow', as: 'conflict_follow'  #route for user to follow individual conflict

  resources :comments



  resources :continents



end

app/models/continent.rb
class Continent < ApplicationRecord
  has_many :conflicts
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController

  #run this for all except index and show.  Check if a user has logged in from application controller.  Not logged in users can still browse the continents and individual continents
  before_action :check_if_logged_in, except: [:index, :show]


  def index
    @continents = Continent.all
  end

  def show
    @continent = Continent.find params[:id]
  end

  def edit
      @continent = Continent.find params[:id]
  end

  def update
    @continent = Continent.find params[:id]
    @continent.update continent_params

    redirect_to continent_path(@continent.id)

  end


  private

  def continent_params
    params.require(:continent).permit(:area, :population, :image)

  end
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/views/continents/_form.html.erb
<%= form_for @continent do |f| %>


<%= f.label :area %>
<%= f.text_field :area %>
<br>
<%= f.label :population %>
<%= f.text_field :population %>
<br>
<%= f.label :image %>
<%= f.text_field :image %>
<br>
<br>
<%= f.submit %>


<% end %>

app/views/continents/edit.html.erb
<h2>Edit: <%= @continent.name %></h2>

<%= render partial: 'form' %>

app/views/continents/index.html.erb
<h2>Continents of the world</h2>




<div class='container'>

  <div class='row'>
  <% @continents.each do |continent|%>

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src=<%= continent.image %> alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= continent.name %></h5>
          <%= link_to "See continent", continent_path(continent.id), class: "btn btn-primary" %><br>
        </div>
      </div>

  <%end  %>
  </div>
</div>

app/views/continents/show.html.erb
<h2>Continent: <%= @continent.name %></h2>

<%= link_to "Update this continent", edit_continent_path(@continent.id) %><br><br>

<img src=<%= @continent.image %> alt=<%= @continent.name %>>
<br>
<br>

<strong>Total land area:</strong> <%= @continent.area %>
<br>
<br>

<strong>Polulation:</strong> <%= @continent.population %>
<br>
<br>

<strong>Current conflicts:</strong>

<ul>
  <% if @continent.conflicts.length ==0 %>
    <p>Nil.  <%= @continent.name %> is at peace.</p>

  <% else %>

    <% @continent.conflicts.each do |con| %>
      <li>
        <%= link_to con.name, conflict_path(con.id) %>
      </li>
    <% end %>
  <% end %>

</ul>

app/views/continents/update.html.erb
<h1>Continents#update</h1>
<p>Find me in app/views/continents/update.html.erb</p>