config/routes.rb
Rails.application.routes.draw do


  get '/login' => 'session#new'  #sign in
  post '/login' => 'session#create'  #route to which sign in form is posted
  delete '/login' => 'session#destroy' #path users use to log out.


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"static_pages#home"


  resources :users

  resources :conflicts

  get '/conflicts/:id/follow'=>'conflicts#follow', as: 'conflict_follow'  #route for user to follow individual conflict

  resources :comments



  resources :continents



end

app/models/conflict.rb
class Conflict < ApplicationRecord
  belongs_to :continent, optional: true
  has_and_belongs_to_many :users
  has_many :comments

end

app/controllers/conflicts_controller.rb
class ConflictsController < ApplicationController

  before_action :check_if_logged_in, except: [:index, :show]


  def new
    @conflict = Conflict.new
  end

  def create
    # Conflict.create conflict_params
    @conflict = Conflict.new(conflict_params)
    # cloundinary upload happens here
    if params[:file].present?
      response = Cloudinary::Uploader.upload params[:file]
      @conflict.image = response["public_id"]
    end
    @conflict.save
    redirect_to conflicts_path
  end

  def index
    @conflicts = Conflict.all
  end

  def show
    @conflict = Conflict.find(params[:id])
  end

  def edit
    @conflict = Conflict.find(params[:id])

  end

  def update
    conflict = Conflict.find(params[:id])
    conflict.update conflict_params  #update using partial conflict_params
    redirect_to conflict_path(conflict.id)

  end

  def destroy
    conflict = Conflict.find(params[:id])
    conflict.destroy
    redirect_to conflicts_path
  end


  def follow
    @current_conflict = Conflict.find(params[:id])  #find current conflict hash

    if @current_user.conflicts.include?(@current_conflict)  #check if user already has conflict
      conflict_name = @current_conflict.name
      flash[:message] = "You are already following "+conflict_name+"."
    else
      @current_user.conflicts << @current_conflict
    end
    redirect_to user_path(@current_user.id)
  end

  private
  def conflict_params
    params.require(:conflict).permit(:name, :country, :conflict_type, :description, :parties, :image, :continent_id, :lat, :lng)  #permission to enter and update these fields
  end
end

app/helpers/conflicts_helper.rb
module ConflictsHelper
end

app/views/conflicts/_form.html.erb
<%= form_for @conflict, html: {multipart: true} do |f| %>   <!--html part for cloudinary -->

  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :country %>
    <%= f.text_field :country %>
  </fieldset>
  <fieldset>
    <%= f.label :conflict_type %>
    <%= f.text_field :conflict_type %>
  </fieldset>
  <fieldset>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </fieldset>
  <fieldset>
    <%= f.label :parties %>
    <%= f.text_field :parties %>
  </fieldset>
  <fieldset>
    <%= f.label :latitude %>
    <%= f.text_field :lat %>
  </fieldset>
  <fieldset>
    <%= f.label :longitude %>
    <%= f.text_field :lng%>
  </fieldset>
  <fieldset>
    <%= f.label :continent_id, 'Continent' %>  <!--drop down selection-->
    <%= f.collection_select :continent_id, Continent.all, :id, :name, prompt: 'Please choose a continent'  %>
  </fieldset>

  <fieldset>
    <%= f.label :image, 'Image URL' %>
    <%= f.text_field :image %>            <!--cloudinary change -->
  </fieldset>
  <%= f.submit %>

<% end %>

app/views/conflicts/create.html.erb
<h1>Conflicts#create</h1>
<p>Find me in app/views/conflicts/create.html.erb</p>

app/views/conflicts/destroy.html.erb
<h1>Conflicts#destroy</h1>
<p>Find me in app/views/conflicts/destroy.html.erb</p>

app/views/conflicts/edit.html.erb
<h2>Edit: <%= @conflict.name %></h2>

<%= render partial: 'form' %>

app/views/conflicts/index.html.erb
<h2 class='display-5'>Where we aren't getting along</h2>


  <div>

    <%= link_to "New conflict?  Add here", new_conflict_path, class: 'btn btn-warning' %>
  </div>


  <!--The div element for the map -->
  <div id="map"></div>


<script>
// Initialize and add the map
var locations = <%= @conflicts.pluck(:lat, :lng, :id, :name, :image).to_json.html_safe %>; //creates an array of arrays

function initMap() {
  // The location of Uluru
  // var uluru = {lat: 25.54, lng: -103.41};
  var bounds = new google.maps.LatLngBounds();  //create boundary box, no fixed dimensions
  // The map, centered at Uluru
  var map = new google.maps.Map(document.getElementById('map'));  //create new map, place map
  // The marker, positioned at Uluru
  // var marker = new google.maps.Marker({position: uluru, map: map});
  var infoWindow = new google.maps.InfoWindow({maxWidth:320});

  for( let i =0; i<locations.length; i++){
    var m = new google.maps.Marker({
      position: {
        lat: locations[i][0],
        lng: locations[i][1]

      },
      map: map,
      content: `<div>${locations[i][3]}</div><img class='windowImg' src=${locations[i][4]}><a href="/conflicts/${locations[i][2]}">Go to conflict</a>`,
      url: `/conflicts/${locations[i][2]}`
    });

    bounds.extend(m.getPosition());  //boundary box stretches by each marker's (m) position
    google.maps.event.addListener(m, 'click', function() {
      infoWindow.setContent(this.content);
      infoWindow.open(this.getMap(), this);

    });

  };  //end for loop

  map.fitBounds(bounds);
  map.setZoom(3);  //centre on selected conflict


}; // initMap()

</script>
  <!--Load the API from the specified URL
  * The async attribute allows the browser to render the page while the API loads
  * The key parameter will contain your own API key (which is not needed for this tutorial)
  * The callback parameter executes the initMap() function
  -->
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBfdeYzd23jyR3fKx0oRtdlqCDK-NEzwcI&callback=initMap">
  </script>

app/views/conflicts/new.html.erb
<h2>Who's getting upset now?</h2>



<%= render partial: 'form' %>

app/views/conflicts/show.html.erb
<h2><%= @conflict.name %></h2>

Continent: <%= link_to @conflict.continent.name, continent_path(@conflict.continent.id) %><br>


Conflict type: <%= @conflict.conflict_type %><br>
Parties involved: <%= @conflict.parties %><br>
Description : <%=simple_format( @conflict.description) %><br>

<%= cl_image_tag @conflict.image, class: 'conflictImage' %>

<%= link_to "Follow this conflict", conflict_follow_path(@conflict) %>
<%= link_to "Delete this conflict", conflict_path(@conflict.id), method: 'delete' %>
<hr>
Comments<br>


  <% @conflict.comments.each do |comment| %>
    <%= comment.comment %><br>
    <%= comment.user.name %>  <br>
    <%= comment.updated_at %><br>
    <%= link_to "Edit comment", edit_comment_path(comment.id)  %> ||
    <%= link_to "Delete comment", comment_path(comment.id), method: 'delete' %>
    <br><br>

  <% end %>
<br>
<br>

<% if flash[:error].present? %>
  <%= flash[:error] %>
<% end %>

<%= form_tag comments_path do %>
  <%= label_tag :comment %>
  <%= text_area_tag :comment %>
  <%= hidden_field_tag :conflict_id, "#{@conflict.id}" %>
<br>
<%= submit_tag "Submit" %>
<% end %>

app/views/conflicts/update.html.erb
<h1>Conflicts#update</h1>
<p>Find me in app/views/conflicts/update.html.erb</p>