config/routes.rb
Rails.application.routes.draw do


  get '/login' => 'session#new'  #sign in
  post '/login' => 'session#create'  #route to which sign in form is posted
  delete '/login' => 'session#destroy' #path users use to log out.


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"static_pages#home"


  resources :users

  resources :conflicts

  get '/conflicts/:id/follow'=>'conflicts#follow', as: 'conflict_follow'  #route for user to follow individual conflict

  resources :comments



  resources :continents



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>


    <script src='//underscorejs.org/underscore-min.js' type='text/javascript'></script>


  </head>

  <body>
    <nav>
    <% if @current_user.present? %>
      You are logged in as <%= link_to @current_user.name, user_path(@current_user.id) %>
      <%= link_to 'Logout', login_path, method: 'delete', class:'logout btn btn-outline-dark' %>

    <% else %>
      <%= link_to 'Login', login_path, class: "btn btn-outline-dark" %>
      <%= link_to 'Sign up', new_user_path, class: "btn btn-outline-dark" %>

    <% end %>

  </nav>


      <hr>
    <h1 class="display-1 text-center">Ongoing Conflicts In Our World</h1>
    <br>
    <h5 class="display-5 text-center">Can't we all just get along?</h3>
    <div class="centre">
      <%= link_to "See All Continents", continents_path, class: 'btn btn-outline-danger'%>
      <%= link_to "See All Conflicts", conflicts_path, class: 'btn btn-outline-danger'%>
    </div>
    <%= yield %>
  </body>
</html>